### ISSUE TITLE
Header written incorrectly if multiple threads used by `make`

### ISSUE THREAD

**Issue by ctrlcctrlv** [jrmarino/fetch-freebsd#3] opened 2020-10-16 14:46 UTC
Took me a bit to track this down.

On Arch, `makepkg` will tell `make` to use multiple threads (e.g. via `-j9`) if so configured by `makepkg.conf`, which, it usually is.

That, on my system, results in broken output like this in both `${CMAKE_CURRENT_BINARY_DIR}/httperr.h` and `${CMAKE_CURRENT_BINARY_DIR}/ftperr.h` (must provide `-DFETCH_LIBRARY=ON`):

```c
static struct fetcherr http_errlist[] = {
    { 100, FETCH_OK, "Continue" },
    { 101, FETCH_OK, "Switching Protocols" },
    { 200, FETCH_OK, "OK" },
    { 201, FETCH_OK, "Created" },
    { 202, FETCH_OK, "Accepted" },
    { 203, FETCH_INFO, "Non-Authoritative Information" },
    { 204, FETCH_OK, "No Content" },
    { 205, FETCH_OK, "Reset Content" },
    { 206, FETCH_OK, "Partial Content" },
    { 300, FETCH_MOVED, "Multiple Choices" },
    { 301, FETCH_MOVED, "Moved Permanently" },
    { 302, FETCH_MOVED, "Moved Temporarily" },
    { 303, FETCH_MOVED, "See Other" },
    { 304, FETCH_OK, "Not Modified" },
    { 305, FETCH_INFO, "Use Proxy" },
    { 307, FETCH_MOVED, "Temporary Redirect" },
    { 308, FETCH_MOVED, "Permanent Redirect" },
    { 400, FETCH_PROTO, "Bad Request" },
    { 401, FETCH_AUTH, "Unauthorized" },
    { 402, FETCH_AUTH, "Payment Required" },
    { 403, FETCH_AUTH, "Forbidden" },
    { 404, FETCH_UNAVAIL, "Not Found" },
    { 405, FETCH_PROTO, "Method Not Allowed" },
    { 406, FETCH_PROTO, "Not Acceptable" },
    { 407, FETCH_AUTH, "Proxy Authentication Required" },
    { 408, FETCH_TIMEOUT, "Request Time-out" },
    { 409, FETCH_EXISTS, "Conflict" },
    { 410, FETCH_UNAVAIL, "Gone" },
    { 411, FETCH_PROTO, "Length Required" },
    { 412, FETCH_SERVER, "Precondition Failed" },
    { 413, FETCH_PROTO, "Request Entity Too Large" },
    { 414, FETCH_PROTO, "Request-URI Too Large" },
    { 415, FETCH_PROTO, "Unsupported Media Type" },
    { 416, FETCH_UNAVAIL, "Requested Range Not Satisfiable" },
    { 417, FETCH_SERVER, "Expectation Failed" },
    { 500, FETCH_SERVER, "Internal Server Error" },
    { 501, FETCH_PROTO, "Not Implemented" },
    { 502, FETCH_SERVER, "Bad Gateway" },
    { 503, FETCH_TEMP, "Service Unavailable" },
    { 504, FETCH_TIMEOUT, "Gateway Time-out" },
    { 505, FETCH_PROTO, "HTTP Version not supported" },
    { 999, FETCH_PROTO, "Protocol error" },
    { 100, FETCH_OK, "Continue" },
    { 101, FETCH_OK, "Switching Protocols" },
    { 200, FETCH_OK, "OK" },
    { 201, FETCH_OK, "Created" },
    { 202, FETCH_OK, "Accepted" },
    { 203, FETCH_INFO, "Non-Authoritative Information" },
    { 204, FETCH_OK, "No Content" },
    { 205, FETCH_OK, "Reset Content" },
    { 206, FETCH_OK, "Partial Content" },
    { 300, FETCH_MOVED, "Multiple Choices" },
    { 301, FETCH_MOVED, "Moved Permanently" },
    { 302, FETCH_MOVED, "Moved Temporarily" },
    { -1, FETCH_UNKNOWN, "Unknown HTTP error" }
    { 303, FETCH_MOVED, "See Other" },
};
    { 304, FETCH_OK, "Not Modified" },
    { 305, FETCH_INFO, "Use Proxy" },
    { 307, FETCH_MOVED, "Temporary Redirect" },
    { 308, FETCH_MOVED, "Permanent Redirect" },
    { 400, FETCH_PROTO, "Bad Request" },
    { 401, FETCH_AUTH, "Unauthorized" },
    { 402, FETCH_AUTH, "Payment Required" },
    { 403, FETCH_AUTH, "Forbidden" },
    { 404, FETCH_UNAVAIL, "Not Found" },
    { 405, FETCH_PROTO, "Method Not Allowed" },
    { 406, FETCH_PROTO, "Not Acceptable" },
    { 407, FETCH_AUTH, "Proxy Authentication Required" },
    { 408, FETCH_TIMEOUT, "Request Time-out" },
    { 409, FETCH_EXISTS, "Conflict" },
    { 410, FETCH_UNAVAIL, "Gone" },
    { 411, FETCH_PROTO, "Length Required" },
    { 412, FETCH_SERVER, "Precondition Failed" },
    { 413, FETCH_PROTO, "Request Entity Too Large" },
    { 414, FETCH_PROTO, "Request-URI Too Large" },
    { 415, FETCH_PROTO, "Unsupported Media Type" },
    { 416, FETCH_UNAVAIL, "Requested Range Not Satisfiable" },
    { 417, FETCH_SERVER, "Expectation Failed" },
    { 500, FETCH_SERVER, "Internal Server Error" },
    { 501, FETCH_PROTO, "Not Implemented" },
    { 502, FETCH_SERVER, "Bad Gateway" },
    { 503, FETCH_TEMP, "Service Unavailable" },
    { 504, FETCH_TIMEOUT, "Gateway Time-out" },
    { 505, FETCH_PROTO, "HTTP Version not supported" },
    { 999, FETCH_PROTO, "Protocol error" },
    { -1, FETCH_UNKNOWN, "Unknown HTTP error" }
};
```

It seems that two threads are both calling `genheaders` at the same time, resulting in a race condition.

Workaround:

```diff
 build() {
...
-       make -C build
+       make -C build -j1
...
 }
```

Obviously, I'm hoping you see fit to commit a real solution which will lock the file in `generate_errors.sh`. I am not good enough at Bash to do it sanely, I don't think, I can tell by your code you're much better with Bash than I.

**Comment by jrmarino** [comment] 2020-10-16 14:52
hmm, it's not a bash issue but rather a CMake issue.
We build with beefy machines with concurrent make processes and I didn't see this, but it was apparently luck.  
Use -j1 for now (it's not that much slower than -j9 as fetch is pretty small program) but I'll leave this issue up and see if a solution via cmake can't be found.

**Comment by ctrlcctrlv** [comment] 2020-10-16 14:53
I guessed locking and unlocking the file in Bash would work, but you're right, that's quite a hack :) 

Perhaps instead of trying to do it sanely, it's best to not do it at all and fix cmake, indeed. Hehe

**Comment by jrmarino** [comment] 2020-10-16 14:54
ah, I get your proposal.  yes, maybe locking would fix it but really that's not the best approach.
(answered simo to your post)

**Comment by jrmarino** [comment] 2020-10-16 15:02
I'm going to take another look at generate_errors.sh.  There's no way it should be combining outputs into one file.

**Comment by ctrlcctrlv** [comment] 2020-10-16 15:15
Cool! I tweeted about your project, I hope people support it: https://twitter.com/fr_brennan/status/1317120199535910913

One of the more useful projects I've come across with 0 :star:. Not that stars are everything, but they tend to at least point to community acceptance :)

**Comment by jrmarino** [comment] 2020-10-16 15:15
So I was thinking it was merging ftp and http in one file, which should be impossible.  Instead it's calling generate_errors.sh twice with same arguments (.e.g. generate_errors.sh ftp ).

**Comment by ctrlcctrlv** [comment] 2020-10-16 15:16
Right. On my system it looked like this...

```
/home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/generate_errors.sh ftp /home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/build/library
/home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/generate_errors.sh ftp /home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/build/library
/home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/generate_errors.sh http /home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/build/library
/home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/generate_errors.sh http /home/fred/Workspace/aur/fetch/src/fetch-freebsd-12.0.8-2/build/library
```

I just wrote into the script...

```bash
echo "$0 $1 $2" >> /tmp/fetch_build
```

**Comment by jrmarino** [comment] 2020-10-16 15:18
(btw I was ejected from FreeBSD community a few years ago after a ton of contribution.  Lots of drama, I was basically screwed, lots of people were unhappy but it's water under the bridge)

**Comment by ctrlcctrlv** [comment] 2020-10-16 15:19
Oh, I'm sorry to hear that. Don't worry about it though. The street cred of once having had a freebsd.org email isn't something that washes off. :-)

**Comment by jrmarino** [comment] 2020-10-16 15:26
I'm not worried. :)
So this issue is legit -- both library and program is generating the file, apparently in the same place.
Either the generation has to be moved out of makefiles or they have to generate in separate directories.
It'll take so fiddling to fix it.  So right now -j1 is required.

**Comment by jrmarino** [comment] 2020-10-16 20:32
by the way, the reason I never hit this is because I never built the program and library together.  FETCH_LIBRARY and FETCH_PROGRAM were always meant to have opposing values.  But I can fix it so they can be built together.

**Comment by jrmarino** [comment] 2020-10-16 23:37
so I think there are 2 things going on here.
1) You set FETCH_LIBRARY=ON.  I doubt you really want this.  Does anything use this library?  The fetch program is very likely all you want (and it doesn't use the library).
2) You built cmake inside the source tree.  I think this is why it's not putting the generated files in separate directories (as it does for me as I build outside the source).

I am going to test this theory.  I might just try to detect insource builds and have it stop.
Likewise just not building the library would solve the issue.

**Comment by jrmarino** [comment] 2020-10-16 23:43
even insource, cmake is building 2 separate generated files (one set in library directory and the other set in program directory).  It must be connected to your -S, -B switches for cmake

**Comment by ctrlcctrlv** [comment] 2020-10-16 23:48
I think normally the rule of the AUR is we build the maximum possible within reason. I might not need the library but someone might, so that's why I tried to build it

**Comment by jrmarino** [comment] 2020-10-16 23:51
well, there has to be software that requires libfetch (and I actually have it set up as two separate ports, one provides the program and one provides the library).

I did notice that I'm still not building with -jX, which I'll try to force, but the files are getting generated in 2 separate directories so it really shouldn't matter.

**Comment by ctrlcctrlv** [comment] 2020-10-17 00:10
Typically separate PKGBUILDs aren't considered the "Arch way of doing things". Arch doesn't have `-dev` packages either for example; headers are always included with everything. Makes using it a lot easier in my opinion, who would even notice the weight of headers these days? But I digress.

If you want, I can easily run cmake twice.

**Comment by jrmarino** [comment] 2020-10-17 00:16
so it turns out I had forced single job (I may have run into the same issue).  When I took it off, I reproduced the issue.  
so the solution (at this time) really is to limit to -j1.
What I suspect is happening is that the generator is trying to read the same files simultaneously.  The output is distinct so I think it's a reading issue.  locking would probably force a sequential read.  Still pondering.

On the other topic, I'd bet money I can find multiple ports that use the same source tarball to generate different products.  I'd bet there are lots of cases of that.  How about Qt5?  We've got like 15 ports all using the same Qt5 giant tarball.  I wouldn't be surprised in Arch does that too.  It's not here nor there, just saying I don't think the approach is unique -- at all.

**Comment by ctrlcctrlv** [comment] 2020-10-17 00:18
You're definitely the expert there &mdash; you wrote a package manager after all.

I make fonts. ;-)

**Comment by jrmarino** [comment] 2020-10-17 00:21
actually ravenports is an analog to arch build system - but operating system agnostic.
So the same recipe builds identical software for BSD, linux, solaris, mac, etc.
But unlike freebsd ports, arch, etc, it's not bash/makefile based.

(we currently use freebsd's pkg as the package manager but I'm in the process of rewriting that, but that's out of scope)

**Comment by jrmarino** [comment] 2020-10-17 02:25
Concurrent building supported in v12.0.9

**Closed by jrmarino** 2020-10-17 02:25 UTC
